#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V #VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a gnome-Terminal desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Sc manage=off

#Load Wallpaper
feh --bg-fill /home/gfrancv/Images/wallpaper.png

#Launch Polybar
~/.config/polybar/./launch.sh --hack

#Follow the mouse
bspc config focus_follows_pointer true

#Round the corners
picom --experimental-backends &
bspc config border_width 2

#Color in the borders when the app is active
bspc config focused_border_color "#3fb19C"
bspc config normal_border_color "#21262b"



